import type { PlatformId, PlatformPresetGroup } from '../types/capture'

export const viewportPresets: PlatformPresetGroup[] = [
  {
    id: 'ios-phone',
    name: '苹果手机',
    shortName: 'iOS',
    description: 'iPhone 视口预设',
    presets: [
      {
        id: 'iphone-390x844',
        name: '390 × 844',
        description: '经典 6.1 英寸 iPhone',
        representativeModels: [
          'iPhone 12',
          'iPhone 12 Pro',
          'iPhone 13',
          'iPhone 13 Pro',
          'iPhone 14',
        ],
        viewport: { width: 390, height: 844 },
        deviceScaleFactor: 3,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'iphone-393x852',
        name: '393 × 852',
        description: '主流 6.1 英寸 iPhone',
        representativeModels: ['iPhone 14 Pro', 'iPhone 15', 'iPhone 15 Pro', 'iPhone 16'],
        viewport: { width: 393, height: 852 },
        deviceScaleFactor: 3,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'iphone-402x874',
        name: '402 × 874',
        description: '6.3 英寸 iPhone',
        representativeModels: ['iPhone 16 Pro', 'iPhone 17', 'iPhone 17 Pro'],
        viewport: { width: 402, height: 874 },
        deviceScaleFactor: 3,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'iphone-430x932',
        name: '430 × 932',
        description: '6.7 英寸大屏 iPhone',
        representativeModels: [
          'iPhone 14 Pro Max',
          'iPhone 15 Plus',
          'iPhone 15 Pro Max',
          'iPhone 16 Plus',
        ],
        viewport: { width: 430, height: 932 },
        deviceScaleFactor: 3,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'iphone-440x956',
        name: '440 × 956',
        description: '6.9 英寸 Pro Max',
        representativeModels: ['iPhone 16 Pro Max', 'iPhone 17 Pro Max'],
        viewport: { width: 440, height: 956 },
        deviceScaleFactor: 3,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
    ],
  },
  {
    id: 'ios-tablet',
    name: '苹果平板',
    shortName: 'iPadOS',
    description: 'iPad 视口预设',
    presets: [
      {
        id: 'ipad-820x1180',
        name: '820 × 1180',
        description: '现代 10.9/11 英寸 iPad · 主要上市于 2022、2024、2025 年',
        representativeModels: ['基础款 iPad', 'iPad Air'],
        viewport: { width: 820, height: 1180 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'ipad-768x1024',
        name: '768 × 1024',
        description: '7.9/9.7 英寸 Home 键 iPad · 主要上市于 2013–2018 年',
        representativeModels: ['iPad', 'iPad Air', 'iPad mini'],
        viewport: { width: 768, height: 1024 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'ipad-810x1080',
        name: '810 × 1080',
        description: '10.2 英寸基础款 iPad · 主要上市于 2019–2021 年',
        representativeModels: ['基础款 iPad'],
        viewport: { width: 810, height: 1080 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
    ],
  },
  {
    id: 'android-phone',
    name: '安卓手机',
    shortName: 'Android',
    description: 'Android 手机视口预设',
    presets: [
      {
        id: 'android-phone-360x800',
        name: '360 × 800',
        description: 'Android 窄屏主流档',
        representativeModels: ['2400 × 1080 @3', '1600 × 720 @2'],
        viewport: { width: 360, height: 800 },
        deviceScaleFactor: 3,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'android-phone-393x873',
        name: '393 × 873',
        description: 'Android 中等逻辑宽度',
        representativeModels: ['约 1080 × 2400'],
        viewport: { width: 393, height: 873 },
        deviceScaleFactor: 2.75,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'android-phone-420x933',
        name: '420 × 933',
        description: 'Android 较宽手机 · 1.5K 屏幕档',
        representativeModels: ['2800 × 1260'],
        viewport: { width: 420, height: 933 },
        deviceScaleFactor: 3,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
    ],
  },
  {
    id: 'android-tablet',
    name: '安卓平板',
    shortName: 'Android',
    description: 'Android 平板视口预设',
    notice: 'DPR 2 为依据采集物理分辨率推算的工程测试值，并非对应型号的真机实测结果。',
    presets: [
      {
        id: 'android-tablet-800x1280',
        name: '800 × 1280',
        description: 'Android 平板主流分辨率档',
        representativeModels: ['2560 × 1600', '1920 × 1200'],
        viewport: { width: 800, height: 1280 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'android-tablet-640x876',
        name: '640 × 876',
        description: '学习机窄屏档',
        representativeModels: ['X3', 'X6', 'A7'],
        viewport: { width: 640, height: 876 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'android-tablet-800x1088',
        name: '800 × 1088',
        description: '步步高学习机主流档',
        representativeModels: ['S6', 'A8', 'S7'],
        viewport: { width: 800, height: 1088 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'android-tablet-800x1164',
        name: '800 × 1164',
        description: '步步高学习机大屏档',
        representativeModels: ['S8', 'S9'],
        viewport: { width: 800, height: 1164 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'android-tablet-720x1100',
        name: '720 × 1100',
        description: '11.5 英寸华为平板档',
        representativeModels: ['HUAWEI MatePad 11.5'],
        viewport: { width: 720, height: 1100 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
      {
        id: 'android-tablet-920x1400',
        name: '920 × 1400',
        description: '11.5 英寸大屏华为平板档',
        representativeModels: ['HUAWEI MatePad 11.5″S'],
        viewport: { width: 920, height: 1400 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
        fullPage: false,
        readySelector: '',
      },
    ],
  },
]

export function getPresetSelectionId(platformId: PlatformId, presetId: string): string {
  return `${platformId}:${presetId}`
}

export function getPlatformPresetIds(platform: PlatformPresetGroup): string[] {
  return platform.presets.map((preset) => getPresetSelectionId(platform.id, preset.id))
}

const defaultApplePhonePlatform = viewportPresets.find((platform) => platform.id === 'ios-phone')

export const defaultSelectedPresetIds = defaultApplePhonePlatform
  ? getPlatformPresetIds(defaultApplePhonePlatform)
  : []
